function [u,e,gap]=CG_BTTB(b,ig,tev,tol,X)
%CG_1 uses the CG method for solving T_{mn}u=b
%b: the right-hand side vector;
%ig: the initial guess for the CG method;
%tev: the eigenvalues generated by gentev.m;
%tol: the tolerance;
%u: the output solution;

mmax=20; %the maximal number of iterations
u=ig;

%r=tx(tev,b)-tx(tev,tx(tev,u));
r=b-1/(2*pi)*tx(tev,u);
e(1)=norm(r,inf);
gap(1) = norm(reshape(u,512,512)-X,2)/norm(X,2);

iter=1;
p=r;
n=length(b);
while iter < mmax & e(iter)/e(1)>tol,
    temp=1/(2*pi)*tx(tev,p);
 %  temp=tx(tev,temp);
    temp1=p'*temp;
    alpha=r'*p/temp1;
    u=u+alpha*p;
    r=r-alpha*temp;
    p=r-((r'*temp)/temp1)*p;
  %  max(abs(p))
   % p=p+randn(n,1);
    iter=iter+1
    e(iter)=norm(r,inf);
    e(iter)/e(1)
    gap(iter) = norm(reshape(u,512,512)-X,2)/norm(X,2);

    myplot(reshape(u,512,512));
%     pause(2);
end
% plot(log10(e))