function [u,e]=CG_RR_BTTB(b,ig,tev,tol,alpha,N)
%Standard Tikhonov regularization with re-weighted CGM
%b: the right-hand side vector;
%ig: the initial guess for the CG method;
%tev: the eigenvalues generated by gentev.m;
%tol: the tolerance;
%u: the output solution;

% N = 15; %the maximal number of iterations
mmax = N;
u=ig;
u0=u;
%r=tx(tev,b)-tx(tev,tx(tev,u));
r=-b;
I0=tx(tev,r);
It=I0;
e(1)=norm(r,inf);
iter=1;
while iter < mmax% & e(iter)/e(1)>tol,
  
    r=tx(tev,u)-b;
    I=tx(tev,r)+alpha*u;
    beta=(norm(I)^2)/(norm(I0)^2);
    I0=I;
    It=I+beta*It;
    k=(It'*I)/(norm(tx(tev,It))^2+alpha*norm(It)^2);
    u=u-k*It;
    if iter<2
        u0=u;
    end
    gamma=(norm(u)^2)/(norm(u0)^2)
    u0=u;
    if gamma >1
     alpha=alpha/gamma;
    end
    alpha
    iter=iter+1
    e(iter)=norm(r,inf);
    e(iter)/e(1)
end
plot(log10(e))